language: ruby

sudo: false # Use container-based infrastructure

cache: bundle

before_install:
  - gem update bundler

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
